# Generated by Django 2.2.5 on 2019-12-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbie', '0002_auto_20191211_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonies',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
