# Generated by Django 2.2.5 on 2020-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbie', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quote', models.CharField(blank=True, max_length=500)),
                ('intro', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image_one', models.ImageField(upload_to='pics')),
                ('image_two', models.ImageField(blank=True, upload_to='pics')),
                ('image_three', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
