# Generated by Django 2.2.5 on 2020-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbie', '0007_auto_20200316_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_Page_title_one', models.CharField(max_length=250)),
                ('home_Page_title_two', models.CharField(max_length=250)),
                ('home_page_title_background', models.ImageField(default='images\\hero_2.jpg', upload_to='pics')),
                ('home_page_title_background_two', models.ImageField(default='images\\hero_1.jpg', upload_to='pics')),
                ('home_page_image_one', models.ImageField(default='images\\img_4.jpg', upload_to='pics')),
                ('home_page_text_one', models.TextField()),
                ('home_page_image_two', models.ImageField(default='images\\img_3.jpg', upload_to='pics')),
                ('home_page_text_two', models.TextField()),
            ],
        ),
    ]
