# Generated by Django 2.2.5 on 2020-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbie', '0008_siteeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteeditor',
            name='home_page_image_one',
            field=models.ImageField(default='pics\\img_4.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='siteeditor',
            name='home_page_image_two',
            field=models.ImageField(default='pics\\img_3.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='siteeditor',
            name='home_page_title_background',
            field=models.ImageField(default='pics/hero_1.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='siteeditor',
            name='home_page_title_background_two',
            field=models.ImageField(default='pics/hero_2.jpg', upload_to='pics'),
        ),
    ]
