# Generated by Django 2.2.5 on 2020-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbie', '0009_auto_20200409_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteeditor',
            name='about_image',
            field=models.ImageField(default='pics\\image_6.jpg', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='siteeditor',
            name='about_text',
            field=models.TextField(null=True),
        ),
    ]
